name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      env:
        SSH_USER: andoladeploy
        SSH_HOST: 45.114.48.221
        PROJECT_PATH: /home/andoladeploy/workspace/Testcrmapp
      run: |
        ssh -p 2222 -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
          cd $PROJECT_PATH
          git pull origin master
          rm -rf .next
          npm install
          npm run build
          pm2 restart github-action  || pm2 start npm --name "github-action" -- start
        EOF
